-- Purpose: Create the three main tables used by the mediator and supporting indexes.
-- Notes:
--  - InputPatientData: raw/inbound temporal records. Many rows per patient allowed.
--    Unique constraint prevents duplicate records with same (PatientId, ConceptName, StartDateTime).
--  - OutputPatientData: abstractions generated by the mediator. Unique constraint prevents duplicate abstractions.
--  - PatientQAScores: QA results for patterns. Unique constraint prevents duplicate QA entries for same (PatientId, PatternName, StartDateTime).

CREATE TABLE IF NOT EXISTS InputPatientData (
    RowId INTEGER PRIMARY KEY AUTOINCREMENT,
    PatientId INTEGER NOT NULL,
    ConceptName TEXT NOT NULL,
    StartDateTime TEXT NOT NULL,
    EndDateTime TEXT NOT NULL,
    Value TEXT NOT NULL,
    Unit TEXT,
    UNIQUE (PatientId, ConceptName, StartDateTime)
);

CREATE TABLE IF NOT EXISTS OutputPatientData (
    RowId INTEGER PRIMARY KEY AUTOINCREMENT,
    PatientId INTEGER NOT NULL,
    ConceptName TEXT NOT NULL,
    StartDateTime TEXT NOT NULL,
    EndDateTime TEXT NOT NULL,
    Value TEXT NOT NULL,
    AbstractionType TEXT NOT NULL,
    UNIQUE (PatientId, ConceptName, StartDateTime)
);

CREATE TABLE IF NOT EXISTS PatientQAScores (
    RowId INTEGER PRIMARY KEY AUTOINCREMENT,
    PatientId INTEGER NOT NULL,
    PatternName TEXT NOT NULL,
    StartDateTime TEXT NOT NULL,
    EndDateTime TEXT,
    Score REAL,
    UNIQUE (PatientId, PatternName, StartDateTime)
);